name: deploy blog
on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          ssh-key: ${{secrets.SSH_PRIVATE_KEY}}
          submodules: true

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.2'
          # extended: true

      # - name: Set private key
      #   uses: webfactory/ssh-agent@v0.4.0
      #   with:
      #     ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Configure git
        run: |
          git config --global user.email "admin@xiaozhu.dev"
          git config --global user.name "rust-bot"

      - name: Deploy
        run: | # same to .../deploy.sh
          set -e
          printf "\033[0;32mDeploying updates to GitHub...\033[0m\n"
          hugo --minify
          cd public
          cp ../README.md ./
          git add .
          msg="rebuilding site $(date)"
          if [ -n "$*" ]; then
            msg="$*"
          fi
          git commit -m "$msg"
          git push origin master && echo "=> commit success"
          git log
          cd ..

      - name: Commit submodule changes
        run: |
          git add .
          git commit -m 'chore: rebuild blog' || exit 0
          git push
